### ISSUE TITLE
Is it convenient to share information about the theory of code implementation? Thank you!

### ISSUE THREAD

**Issue by githublqs** [yulongshan/ICP_COV#1]

**Comment by yulongshan** [comment]
references:
1.An ICP variant using a point to line metric —— pl-icp theory
2.An accurate closed-form estimate of ICP'S covariance - covariance estimate
3. A Closed-form Estimate of 3D ICP Covariance - extend 2d to 3d and it has opensource code in github.
4.Observability, Covariance and Uncertainty of ICP Scan Matching - Observability.

And there is CSM package in Andrea Censi personal website which contains pl-icp and covariance code.

I hope these references can help you!  and if you come from china. you can also see my blog https://zhuanlan.zhihu.com/p/367705790.



________________________________
From: githublqs ***@***.***>
Sent: Friday, May 7, 2021 11:05 PM
To: yulongshan/ICP_COV ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yulongshan/ICP_COV] Is it convenient to share information about the theory of code implementation? Thank you! (#1)

**Comment by githublqs** [comment]
感谢！
